"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { Toaster } from "react-hot-toast";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const inter = Inter({ subsets: ["latin"] });

const queryCLient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryCLient}>
          <GoogleOAuthProvider clientId="183129528736-0pdjtqqj34o9olmcqhc4cql219cd6iaq.apps.googleusercontent.com">
            {children}
            <Toaster />
            <ReactQueryDevtools/>
          </GoogleOAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
